name: Create Epic
on:
  milestone:
    types: [created]

jobs:
  create-epic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fdmedia-io/github-clubhouse-actions@master
        with:
          token: ${{ secrets.CLUBHOUSE_TOKEN }}
          owner-name: flowdee
